apiVersion: apps/v1
kind: Deployment
metadata:
  name: lafleet-iot-server
  namespace: default
  labels:
    app: iotServer
    project: lafleet
spec:
  selector:
    matchLabels:
      app: iotServer
  replicas: 1
  template:
    metadata:
      name: iotServer
      labels:
        app: iotServer
    spec:
      containers:
      - name: IMAGE_REPO_NAME_VALUE
        image: IMAGE_VALUE
        env:
        - name: ENDPOINT
          value: "IOT_ENDPOINT"
        - name: STREAMID_REQUEST_TOPIC
          value: "STREAMID_REQUEST_TOPIC_VALUE"
        - name: STREAMID_REPLY_TOPIC
          value: "STREAMID_REPLY_TOPIC_VALUE"
        - name: CA_FILE
          value: "./certs/root-ca.crt"
        - name: CERT_FILE
          value: "./certs/certificate.pem.crt"
        - name: KEY_FILE
          value: "./certs/private.pem.key"
        resources:
          limits:
            memory: "60Mi"
            cpu: "80m"
          requests:
            memory: "30Mi"
            cpu: "40m"
      nodeSelector:
        nodegroup-type: backend-standard