apiVersion: v1
kind: Service
metadata:
  name: redisearch-service
  namespace: default
  labels:
    app: redisearch-svc
    project: lafleet
spec:
  selector:
    app: redisearch-app
  type: ClusterIP
  ports:
  - name: redis-service
    port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisearch
  namespace: default
  labels:
    app: redisearch
    project: lafleet
spec:
  selector:
    matchLabels:
      app: redisearch-app
  replicas: 1
  template:
    metadata:
      labels:
        app: redisearch-app
        project: lafleet
    spec:
      containers:
      - name: redisearch
        image: redislabs/redisearch:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
          requests:
            memory: "25Mi"
            cpu: "50m"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
      nodeSelector:
        nodegroup-type: backend-compute
      tolerations:
      - key: "dedicated-compute"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
