apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: PROJECT_NAME-cluster
  region: AWS_REGION_VALUE
  version: "1.23"

vpc:
  nat:
    gateway: Single
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

managedNodeGroups:
- name: ng-compute-x64
  instanceType: COMPUTE_INSTANCE_TYPE
  instancePrefix: lf-c6i
  minSize: 0
  desiredCapacity: 1
  maxSize: 2
  volumeSize: 20
  volumeType: gp3
  maxPodsPerNode: 30
  privateNetworking: true
  spot: USE_SPOT_INSTANCES
  labels:
    nodegroup-type: backend-compute
  taints:
    - key: dedicated-compute
      value: "true"
      effect: NoSchedule
  tags:
    nodegroup-role: bc
  updateConfig:
    maxUnavailable: 1
- name: ng-standard-x64
  instanceType: STANDARD_INSTANCE_TYPE
  instancePrefix: lf-t3
  minSize: 0
  desiredCapacity: 2
  maxSize: 3
  volumeSize: 20
  volumeType: gp3
  maxPodsPerNode: 30
  privateNetworking: true
  spot: USE_SPOT_INSTANCES
  labels:
    nodegroup-type: backend-standard
  tags:
    nodegroup-role: bm
  updateConfig:
    maxUnavailable: 1
  iam:
    withAddonPolicies:
      externalDNS: true
      certManager: true

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: PROJECT_NAME-eks-sa-sqsdeviceconsumer
      labels: {aws-usage: "application"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        Resource: 'RES_DEVICE_SQS_QUEUE'
      - Effect: Allow
        Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:DescribeLogStreams"
        - "logs:PutLogEvents"
        Resource: '*'
  - metadata:
      name: PROJECT_NAME-eks-sa-sqsshapeconsumer
      labels: {aws-usage: "application"}
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        Resource: 'RES_SHAPE_SQS_QUEUE'
      - Effect: Allow
        Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:DescribeLogStreams"
        - "logs:PutLogEvents"
        Resource: '*'
      - Effect: Allow
        Action:
        - "s3:GetObject"
        - "s3:GetObjectVersion"
        Resource: 'RES_S3_SHAPE_REPO'
